#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx on your web-01 server
TEXT="location /redirect_me {\\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}\\n"
apt-get -y update
apt-get -y install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#  it must return a page that contains the string Holberton School
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "42i $TEXT" /etc/nginx/sites-available/default
service nginx restart