#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page
# 0 Install nginx on web-01 server
apt-get -y update
apt-get -y install nginx
# 1 Return a page that contains the string Holberton School
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
# 2 redirection must be a “301 Moved Permanently”
HOME="location /redirect_me {\\n\\t\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\\t}\\n"
sudo sed -i "19i $HOME" /etc/nginx/sites-available/default
# 3 HTTP 404 error code page that contains the string Ceci n'est pas une page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
CUSTOM="error_page 404 /404.html;\\n\\tlocation = /404.html {\\n\\t\\troot /var/www/html;\\n\\t\\tinternal;\\n\\t}\\n"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
service nginx restart