#!/usr/bin/env bash
# Install nginx on server
apt-get -y update
apt-get -y install nginx

#  Must return a page that contains the string Holberton School
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# /redirect_me is redirecting to another page
sed -i '/listen [::]:80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Custom 404 page that contains the string Ceci n'est pas une page.
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default

# custom Nginx response header
sed -i "/index index.html index.htm index.nginx-debian.html;/a add_header X-Served-By $(cat /etc/hostname);" /etc/nginx/sites-enabled/default

# start service
service nginx start
