#!/usr/bin/env bash
# Set the server to listen on port 80
sed -i "s/listen 8080 default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sed -i "s/listen [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server;/g" /etc/nginx/sites-enabled/default
service nginx start
