#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
PID=$$
echo $PID > /var/run/holbertonscript.pid
 while ((1))
    do
       echo "To infinity and beyond"
       sleep 2
       trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit 1' SIGTERM
       trap 'echo "Y U no love me?!"' SIGINT
       trap 'rm /var/run/holbertonscript.pid' SIGQUIT
 done
