#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hour="Hour: "
h="0"

 while (("$h"<=12))
    do
       echo "$hour$h"
       m="1"
       while (("$m"<=59))
          do
          echo "$m"
          ((m++))
       done
       ((h++))
 done
