#!/usr/bin/env bash
# Bash script that configures localhost and facebook

sudo cp /etc/hosts ~/new_hosts
sed -i "s/127.0.0.1/127.0.0.2/g" ~/new_hosts
echo "8.8.8.8 facebook.com" >> ~/new_hosts
sudo cp -f ~/new_hosts /etc/hosts
