#!/usr/bin/env bash
# Run Nginx as Nginx
sudo chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
